<!DOCTYPE html>
<html lang="en" class="h-full bg-gray-100">

<head>
    <?php include __DIR__ . '/include/head.phtml' ?>
</head>

<body class="h-full">
    <div class="min-h-full ">
        <nav class="bg-gray-800">
            <div class="mx-auto max-w-7xl px-4">
                <div class="flex items-center justify-start gap-4 h-16">
                    <a href="/index.php"
                        class="nav-item text-white py-2 px-3 leading-lg rounded-lg hover:bg-gray-900 transition-all duration-[0.5s]">Home</a>

                    <a href="/contact.php"
                        class="nav-item text-white py-2 px-3 leading-lg rounded-lg hover:bg-gray-900 transition-all duration-[0.5s]">Contact</a>
                </div>
            </div>
        </nav>


        <header class="bg-white">
            <div class="mx-auto max-w-7xl py-5 px-8">
                <h1 class="text-3xl leading-9 font-bold text-gray-900"">Home</h1>
            </div>
        </header>

        <main>
            <div class=" mx-auto max-w-7xl py-5 px-8">
                    O main content here
            </div>
            </main>
    </div>



</body>

</html>